### PR TITLE
footer and cards updated

### PR DESCRIPTION
**Pull request by prathmeshkhandelwal1**

### CODE REVIEW

**Comment by prathmeshkhandelwal1** [comment]
Screenshot (64)

**Comment by prathmeshkhandelwal1** [comment]
#10 and #8 these issues are also fixed in this pr @yashshah2820

**Comment by theyashshahs** [comment]
@prathmeshkhandelwal1 the height of the footer is bit more than it needs to be

**Comment by prathmeshkhandelwal1** [comment]
@yashshah2820 it will resolve when we will implement other design. and also i made it little bit shorter than the design ;)
So, Can you review it plz?

**Comment by prathmeshkhandelwal1** [comment]
@yashshah2820 Any update on this.?

**Review by theyashshahs — APPROVED** [review]

**Pull request merged**
