### PR TITLE
Created contact page 

### LINKED ISSUE #11: create components for the contact us page

### PR DESCRIPTION
**Pull request by nlok5923**
Fixes : #11 

developed UI : 
Screenshot (1371)

deployment link : https://jolly-aryabhata-2ca798.netlify.app/

### CODE REVIEW

**Comment by nlok5923** [comment]
@iiitv/project-maintainers please review this pull request.

**Review by theyashshahs — CHANGES_REQUESTED** [review]
Please stick to the design theme for all the pages

**Comment by nlok5923** [comment]
@yashshah2820 sir i will create a new one aligned with theme.

**Comment by nlok5923** [comment]
@yashshah2820  sir please review this UI.

**Review by theyashshahs — APPROVED** [review]

**Pull request merged**
